spring:
  application:
    name: msf-web
  profiles:
      active: online
      js-version: 2018101402
      css-version: 2018101402
  #模板引擎
  freemarker:
    template-loader-path: classpath:/templates/
    settings-classic-compatible: true