spring:
  application:
    name: msf-web
  profiles:
      active: dev
      js-version: 20181013
      css-version: 20181013
  #模板引擎
  freemarker:
    template-loader-path: classpath:/templates/
    settings-classic-compatible: true